### ISSUE TITLE
Need more content on Active Record Queries prior/on this lab

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/flatiron-bnb-methods#16]
I have heard from a few students that this lab seemed to come out of no where. I think we need to supply them with some more information / labs on Active Record queries. It might also be good to nudge them in the direction of http://guides.rubyonrails.org/active_record_querying.html if they're not already familiar with it. 

@AnnJohn

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
