### ISSUE TITLE
Students not clear as to why use AR of Ruby

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/flatiron-bnb-methods#17]
When I was talking with some students, it wasn't clear to them that making many DB calls to perform these queries in Ruby was a bad idea. Point out that this can result in a lot of DB calls be be very expensive.

**Comment by aturkewi** [comment]
@AnnJohn

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
