### ISSUE TITLE
Change curriculum to look more like upcase progression

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/flatiron-bnb-methods#21]
We should follow the structure upcase follows:
1. Where 
   A. Combining a belongs to model
2. Joins
3. Query methods with other models where(users: name: 'bob')
4. Using merge

B. Combining with has many
- Joins with has many, through 

C. Aggregate methods 

https://thoughtbot.com/upcase/videos/advanced-querying-custom-joins

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
