### ISSUE TITLE
Issues with instructions for "city_openings"

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/flatiron-bnb-methods#22]
Further explanation or clarification would be super helpful here since listings don't have dates. Listings have reservations with checkin and checkout dates, but that doesn't seem to be what the method is asking for. In fact, reservations are the ONLY object with a date attribute but they doesn't really fit the description of "all the available listings given a date range"... what the heck is an _available_ listing? 

For reference, here is the listing schema:

create_table "listings", force: :cascade do |t|
    t.string   "address"
    t.string   "listing_type"
    t.string   "title"
    t.text     "description"
    t.decimal  "price",           precision: 8, scale: 2
    t.integer  "neighborhood_id"
    t.integer  "host_id"
    t.datetime "created_at",                              null: false
    t.datetime "updated_at",                              null: false
end

**Comment by gj** [comment]
> In fact, reservations are the ONLY object with a date attribute but they doesn't really fit the description of "all the available listings given a date range"... what the heck is an available listing?

As I read it, an 'available listing' is a listing that isn't booked during a specified time period. That is, a listing that doesn't have any reservations overlapping with the specified time period.

**Comment by jessenovotny** [comment]
Gotcha, I feel like that could be more clear.

After inspecting the solution, I decided to skip this lab for now; my first
time doing so. I feel like this lab is ill-placed based on it's level of
difficulty. Especially since the following labs went back to basic
associations, this time in Rails. Don't get me wrong, I love the curriculum
and course in general! I am so happy I chose to go with Flatiron :)

Just my honest feedback and observations.

Cheers,
Jesse

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
