### ISSUE TITLE
Tests for #city_openings and #neighborhood_openings are wrong

### ISSUE THREAD

**Issue by lair001** [learn-co-curriculum/flatiron-bnb-methods#24]
I'm pretty sure that these tests are wrong.  In rails_helper.rb, only @reservation4 overlaps with the given range and it belongs to @listing1.  The tests are looking for the presence of @listing2.

**Comment by gj** [comment]
Both tests look fine to me 🙂

**Comment by lair001** [comment]
Looks like I was fairly explicit on the issue so please elaborate on your position.  Please let me know if you need a further explanation.

**Comment by gj** [comment]
> Looks like I was fairly explicit on the issue so please elaborate on your position. Please let me know if you need a further explanation.

Your logic is backward. 🙂

**Comment by christinalcole** [comment]
Hi, Gabe...there does appear to be something 'off' with the city_openings spec in the master branch (the solution branch has the same tests, but objects are created in the spec file, not by referencing rails_helper.rb).  When I test same code against a seeded database (using rails console), against city_spec.rb (master branch) and city_spec.rb (solution branch), only city_spec.rb (master) yields failing results.  Still researching possible causes...

**Comment by cbrazil** [comment]
I second what @christinalcole commented above. Not totally sure what's going on, but there seems to be a discrepancy between the city_openings spec in the master branch and the same spec in the solution branch. Tests pass for the solution branch and in the console but not for the master branch spec. Please advise!

**Comment by christinalcole** [comment]
Following up here: there does appear to be a problem with the `master` branch `city_spec.rb`, but it seems to be related to a validation in the Reservation model.  Please see Issue 30 for details.

**Comment by gj** [comment]
@christinalcole @cbrazil write code based on master branch specs. Solution branch is out-of-date.

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
