### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by bedle88** [learn-co-curriculum/flatiron-bnb-methods#25]
I believe others have raised concerns on this lesson, but just adding my own voice... this feels out of place to me and also totally overwhelmed me. I looked at the solution and I could have googled and stared at it for weeks and I wouldn't have passed all of the tests. Ultimately, looking at fellow student's solutions was way more helpful than the actual solution because some of the code in the actual solution looks foreign to me (like '.merge(Listing.available(start_date, end_date))', '.try', 'joins', 'where.not').

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
