### ISSUE TITLE
Issue with review test

### ISSUE THREAD

**Issue by rmullig2** [learn-co-curriculum/flatiron-bnb-methods#27]
The last test in the review_spec appears to be testing for an overlapping reservation. The new_res reservation it creates does not overlap and will come up as valid if your code is correct. The checkin date needs to be moved back so that it overlaps with an existing reservation in order for the test to be valid.

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
