### ISSUE TITLE
solution tests are different from master branch

### ISSUE THREAD

**Issue by survivingknowledge** [learn-co-curriculum/flatiron-bnb-methods#28]
after much toiling about, the tests that pass in the solution branch are different from the tests in the master branch. So the solution doesn't work for the master branch. Not sure if they just updated the lab without changing the tests in solution branch.

specifically the city_spec.rb tests
where code in solution gives passsing to listing 1,2 but this would fail in master tests as it expects listing2/3 and not listing 1. listing.merge(Listing.available(dates)) would not work for new lab/master

**Comment by survivingknowledge** [comment]
here is code that passes the new lab tests
def city_openings(start_date,end_date)
    ed = Date.parse(end_date)
    sd = Date.parse(start_date)

    self.listings.select do |listing|
      #need to loop through all reservations
      listing.reservations.all? do |res|
        #is any reservation within the date range
        # (StartDate1 <= EndDate2) and (StartDate2 <= EndDate1)
        res.checkin <= ed && res.checkout <= sd
      end
    end
  end

**Comment by gj** [comment]
> Not sure if they just updated the lab without changing the tests in solution branch.

This is the case. If you're interested, compare commit histories for [master](https://github.com/learn-co-curriculum/flatiron-bnb-methods/commits/master) and [solution](https://github.com/learn-co-curriculum/flatiron-bnb-methods/commits/solution) to see divergence.

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
