### ISSUE TITLE
need to add make_reviews to seeds method

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/flatiron-bnb-methods#29]
In seeds.rb, a call to the make_reviews method is missing in the definition of make_seeds.  The review function is defined, just needs to be added to the method call: 

```
def make_seeds
  make_cities
  make_neighborhoods
  make_users
  make_listings
  make_reservations
  make_reviews # this line is needed to seed with Review objects, for console testing
end
```

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
