### ISSUE TITLE
problem with Reservation model validation causes master-branch failure for city_spec

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/flatiron-bnb-methods#30]
One of the validation requirements for the Reservation model is that it "validates a reservation is available" at checkin, checkout; implementation checks the proposed reservation dates against existing reservations for that same listing.  Although the `master` and `solution` branch specs differ slightly in terms of how test objects are created, the following code will pass both branches' `reservation_spec.rb`: 

```
def is_available 
    Reservation.where(listing_id: listing).where.not(id: id).each do |res|
      if (checkin && checkout) && (res.checkin..res.checkout === (checkin..checkout))
        errors.add(:guest, "Sorry: this listing is not available for your desired dates")
      end
    end
  end
```

This validation, however, prevents certain test statements from properly executing in the `master` branch `rails_helper.rb`, specifically lines 62 and 63 (creating 2 reservations) and iteration of the #make_denver loop defined at lines 84-96 (loop executes once, then stops).  Inspection of errors associated with these lines in a pry session traces back to Reservation's #is_available (attached)

<img width="566" alt="screen shot 2017-04-02 at 12 18 52" src="https://cloud.githubusercontent.com/assets/15614698/24589144/723b464a-17a3-11e7-9a7a-140470ade76c.png">

Adjusting #is_available to check each date individually instead of as a range (i.e., as per the `solution` branch) doesn't change the observed outcome with regards to the `master` branch specs/validation failures during testing.

Impacted tests in `master`, `city_spec.rb` are lines 145-173, relating to the the model's instance and class methods.

**Comment by sgharms** [comment]
Hello, we're deploying a brand new version of this lab which will address these pain points. It's a fundamental change to the lab in both code and README and we've built your suggestions / bug reports into this rewrite. We're tracking that work in: https://github.com/learn-co-curriculum/flatiron-bnb-methods/issues/32.

When we close that out, this issue will be addressed. We're going to build this issue into #32 and are going to close this one in the meantime. Thanks for your help and patience.
