### ISSUE TITLE
Error with rails db:migrate

### ISSUE THREAD

**Issue by afteralec** [learn-co-curriculum/flatiron-bnb-methods#33]
`rails db:migrate` throws an error the first time you run it in this lab with error code of:

```
Sprockets::Railtie::ManifestNeededError: Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
```

After doing `mkdir app/assets/config` and `touch app/assets/config/manifest.js`, I can run `rails db:migrate` and `rails db:migrate RAILS_ENV=test` and see the Learn rspec output. This looks like it just needs the manifest file!

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
